url: "https://practice.expandtesting.com/notes/app/login"
api_url: "https://practice.expandtesting.com/notes/api"
email: "velmaakshaya249@gmail.com"
password: "lucky@2209"
grid_url: "http://localhost:4444/wd/hub"
run_on_grid: true